# Generated by Django 2.2.6 on 2019-11-10 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodItem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField()),
                ('process_step', models.CharField(max_length=50)),
                ('schedule', models.TimeField()),
                ('assigned', models.CharField(max_length=30)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodItem.FoodItemsAvailable')),
            ],
        ),
    ]
