# Generated by Django 2.2.6 on 2019-11-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodItem', '0002_processstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='schedule',
            field=models.CharField(max_length=10),
        ),
    ]
