# Generated by Django 2.2.6 on 2019-11-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodItem', '0004_auto_20191111_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='assigned',
            field=models.CharField(max_length=30),
        ),
    ]
